//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input Settings/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""HandPlayer"",
            ""id"": ""c1ac7689-e09a-4ff1-a8df-226bbf43d7c6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""9db91202-30c9-4195-858f-38f7351038c8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HandMove"",
                    ""type"": ""Value"",
                    ""id"": ""25075dc6-e018-48e5-9e70-fce766a278ea"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HandVertical"",
                    ""type"": ""Value"",
                    ""id"": ""70752e34-6c47-401f-adbe-c28aac266efb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AlternateMode"",
                    ""type"": ""Button"",
                    ""id"": ""f86795b6-b40e-4d9c-be66-2f02b457b185"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""9f660d2a-74a1-4db8-9edc-4cf8ecb365fc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold,Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""222e374f-652f-4241-938d-5dae50f3ee92"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""1131edf5-0ba1-41e3-90d9-9ccbd45324b5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""7e71238b-e1cc-476a-bbde-7a74d0a2c0a8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1f89a867-5949-46fb-9180-d4e179c1e8be"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cc2291ae-b9d5-4c1d-bbda-f43943e0b250"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""07f8ef25-9af1-4034-a2b2-9d2168fefeaf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ff28e727-169b-4589-9350-bc62d1c471bb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d2e974e3-19d0-499b-8624-48bbc5731475"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""efd132e4-1528-4011-8bf2-7809d9977a46"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandVertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""bf906d1a-506a-47f6-8727-d5ca82799b05"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""f7952fd4-08e7-4112-815e-23c27bc001fe"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4c08f178-f4e2-474d-b7b6-d84e01e2ff20"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlternateMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e632372-8764-4486-ba69-a1a8663c86dd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""010f3875-5cfb-4611-8da9-3293959e00eb"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08b9aa58-31b2-4942-bad4-2051c8a2c0c1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""EyePlayer"",
            ""id"": ""8288287b-700d-4269-aac5-4b9c1df02a6b"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""4fc78d7d-4ab2-4558-b4b0-0deddae55c5a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""e89d63b4-7d08-4b7b-9ad5-ab366fb60452"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""924666a8-448a-4248-963b-67c9fa32f84b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""e58d910b-5f16-4059-b21d-704df8be7f4c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b948ae68-08ed-43af-b582-6740e0e425fb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""487c7215-75c1-4056-91ed-3078367ecc48"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b7c9d9e4-d686-4c09-9777-9cf61655651a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""96d58f80-ab0e-4cc8-89b1-5a5e9f753f03"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""67f06c87-a71c-4b16-8119-b1ba837a7d2e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""49554d94-6e3b-4726-8290-2228ea6df196"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de85c922-563d-4323-b246-06d7a8db18ab"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4910c52f-046c-4919-b832-a058f3f614ec"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // HandPlayer
        m_HandPlayer = asset.FindActionMap("HandPlayer", throwIfNotFound: true);
        m_HandPlayer_Move = m_HandPlayer.FindAction("Move", throwIfNotFound: true);
        m_HandPlayer_HandMove = m_HandPlayer.FindAction("HandMove", throwIfNotFound: true);
        m_HandPlayer_HandVertical = m_HandPlayer.FindAction("HandVertical", throwIfNotFound: true);
        m_HandPlayer_AlternateMode = m_HandPlayer.FindAction("AlternateMode", throwIfNotFound: true);
        m_HandPlayer_Grab = m_HandPlayer.FindAction("Grab", throwIfNotFound: true);
        m_HandPlayer_Look = m_HandPlayer.FindAction("Look", throwIfNotFound: true);
        m_HandPlayer_Jump = m_HandPlayer.FindAction("Jump", throwIfNotFound: true);
        // EyePlayer
        m_EyePlayer = asset.FindActionMap("EyePlayer", throwIfNotFound: true);
        m_EyePlayer_Move = m_EyePlayer.FindAction("Move", throwIfNotFound: true);
        m_EyePlayer_Look = m_EyePlayer.FindAction("Look", throwIfNotFound: true);
        m_EyePlayer_Interact = m_EyePlayer.FindAction("Interact", throwIfNotFound: true);
        m_EyePlayer_Jump = m_EyePlayer.FindAction("Jump", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_HandPlayer.enabled, "This will cause a leak and performance issues, PlayerControls.HandPlayer.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_EyePlayer.enabled, "This will cause a leak and performance issues, PlayerControls.EyePlayer.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // HandPlayer
    private readonly InputActionMap m_HandPlayer;
    private List<IHandPlayerActions> m_HandPlayerActionsCallbackInterfaces = new List<IHandPlayerActions>();
    private readonly InputAction m_HandPlayer_Move;
    private readonly InputAction m_HandPlayer_HandMove;
    private readonly InputAction m_HandPlayer_HandVertical;
    private readonly InputAction m_HandPlayer_AlternateMode;
    private readonly InputAction m_HandPlayer_Grab;
    private readonly InputAction m_HandPlayer_Look;
    private readonly InputAction m_HandPlayer_Jump;
    public struct HandPlayerActions
    {
        private @PlayerControls m_Wrapper;
        public HandPlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_HandPlayer_Move;
        public InputAction @HandMove => m_Wrapper.m_HandPlayer_HandMove;
        public InputAction @HandVertical => m_Wrapper.m_HandPlayer_HandVertical;
        public InputAction @AlternateMode => m_Wrapper.m_HandPlayer_AlternateMode;
        public InputAction @Grab => m_Wrapper.m_HandPlayer_Grab;
        public InputAction @Look => m_Wrapper.m_HandPlayer_Look;
        public InputAction @Jump => m_Wrapper.m_HandPlayer_Jump;
        public InputActionMap Get() { return m_Wrapper.m_HandPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HandPlayerActions set) { return set.Get(); }
        public void AddCallbacks(IHandPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_HandPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HandPlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @HandMove.started += instance.OnHandMove;
            @HandMove.performed += instance.OnHandMove;
            @HandMove.canceled += instance.OnHandMove;
            @HandVertical.started += instance.OnHandVertical;
            @HandVertical.performed += instance.OnHandVertical;
            @HandVertical.canceled += instance.OnHandVertical;
            @AlternateMode.started += instance.OnAlternateMode;
            @AlternateMode.performed += instance.OnAlternateMode;
            @AlternateMode.canceled += instance.OnAlternateMode;
            @Grab.started += instance.OnGrab;
            @Grab.performed += instance.OnGrab;
            @Grab.canceled += instance.OnGrab;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        private void UnregisterCallbacks(IHandPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @HandMove.started -= instance.OnHandMove;
            @HandMove.performed -= instance.OnHandMove;
            @HandMove.canceled -= instance.OnHandMove;
            @HandVertical.started -= instance.OnHandVertical;
            @HandVertical.performed -= instance.OnHandVertical;
            @HandVertical.canceled -= instance.OnHandVertical;
            @AlternateMode.started -= instance.OnAlternateMode;
            @AlternateMode.performed -= instance.OnAlternateMode;
            @AlternateMode.canceled -= instance.OnAlternateMode;
            @Grab.started -= instance.OnGrab;
            @Grab.performed -= instance.OnGrab;
            @Grab.canceled -= instance.OnGrab;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        public void RemoveCallbacks(IHandPlayerActions instance)
        {
            if (m_Wrapper.m_HandPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHandPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_HandPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HandPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HandPlayerActions @HandPlayer => new HandPlayerActions(this);

    // EyePlayer
    private readonly InputActionMap m_EyePlayer;
    private List<IEyePlayerActions> m_EyePlayerActionsCallbackInterfaces = new List<IEyePlayerActions>();
    private readonly InputAction m_EyePlayer_Move;
    private readonly InputAction m_EyePlayer_Look;
    private readonly InputAction m_EyePlayer_Interact;
    private readonly InputAction m_EyePlayer_Jump;
    public struct EyePlayerActions
    {
        private @PlayerControls m_Wrapper;
        public EyePlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_EyePlayer_Move;
        public InputAction @Look => m_Wrapper.m_EyePlayer_Look;
        public InputAction @Interact => m_Wrapper.m_EyePlayer_Interact;
        public InputAction @Jump => m_Wrapper.m_EyePlayer_Jump;
        public InputActionMap Get() { return m_Wrapper.m_EyePlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EyePlayerActions set) { return set.Get(); }
        public void AddCallbacks(IEyePlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_EyePlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EyePlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        private void UnregisterCallbacks(IEyePlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        public void RemoveCallbacks(IEyePlayerActions instance)
        {
            if (m_Wrapper.m_EyePlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEyePlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_EyePlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EyePlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EyePlayerActions @EyePlayer => new EyePlayerActions(this);
    public interface IHandPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnHandMove(InputAction.CallbackContext context);
        void OnHandVertical(InputAction.CallbackContext context);
        void OnAlternateMode(InputAction.CallbackContext context);
        void OnGrab(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
    public interface IEyePlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
}
